name: bookle
description: "A simple booking system."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0-171.0.dev

dependencies:
  backstreets_widgets: ^0.34.0
  cupertino_icons: ^1.0.8
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  path: ^1.9.1
  path_provider: ^2.1.5
  recase: ^4.1.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  drift_dev: ^2.26.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
